#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linqadvanced
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HR")]
	public partial class HRClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEmployee1(Employee1 instance);
    partial void UpdateEmployee1(Employee1 instance);
    partial void DeleteEmployee1(Employee1 instance);
    partial void InsertPosition(Position instance);
    partial void UpdatePosition(Position instance);
    partial void DeletePosition(Position instance);
    #endregion
		
		public HRClassDataContext() : 
				base(global::linqadvanced.Properties.Settings.Default.HRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HRClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Employee1> Employee1s
		{
			get
			{
				return this.GetTable<Employee1>();
			}
		}
		
		public System.Data.Linq.Table<Position> Positions
		{
			get
			{
				return this.GetTable<Position>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cEmployeeCode;
		
		private string _vFirstName;
		
		private string _vLastName;
		
		private string _cCandidateCode;
		
		private string _vAddress;
		
		private string _cCity;
		
		private string _cState;
		
		private string _cZip;
		
		private string _cCountryCode;
		
		private string _cPhone;
		
		private string _vQualification;
		
		private System.Nullable<System.DateTime> _dBirthDate;
		
		private System.Nullable<char> _cSex;
		
		private string _cCurrentPosition;
		
		private string _cDesignation;
		
		private string _cEmailId;
		
		private string _cDepartmentCode;
		
		private string _cRegion;
		
		private System.Data.Linq.Binary _imPhoto;
		
		private System.Nullable<System.DateTime> _dJoiningDate;
		
		private System.Nullable<System.DateTime> _dResignationDate;
		
		private string _cSocialSecurityNo;
		
		private string _cSupervisorCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncEmployeeCodeChanging(string value);
    partial void OncEmployeeCodeChanged();
    partial void OnvFirstNameChanging(string value);
    partial void OnvFirstNameChanged();
    partial void OnvLastNameChanging(string value);
    partial void OnvLastNameChanged();
    partial void OncCandidateCodeChanging(string value);
    partial void OncCandidateCodeChanged();
    partial void OnvAddressChanging(string value);
    partial void OnvAddressChanged();
    partial void OncCityChanging(string value);
    partial void OncCityChanged();
    partial void OncStateChanging(string value);
    partial void OncStateChanged();
    partial void OncZipChanging(string value);
    partial void OncZipChanged();
    partial void OncCountryCodeChanging(string value);
    partial void OncCountryCodeChanged();
    partial void OncPhoneChanging(string value);
    partial void OncPhoneChanged();
    partial void OnvQualificationChanging(string value);
    partial void OnvQualificationChanged();
    partial void OndBirthDateChanging(System.Nullable<System.DateTime> value);
    partial void OndBirthDateChanged();
    partial void OncSexChanging(System.Nullable<char> value);
    partial void OncSexChanged();
    partial void OncCurrentPositionChanging(string value);
    partial void OncCurrentPositionChanged();
    partial void OncDesignationChanging(string value);
    partial void OncDesignationChanged();
    partial void OncEmailIdChanging(string value);
    partial void OncEmailIdChanged();
    partial void OncDepartmentCodeChanging(string value);
    partial void OncDepartmentCodeChanged();
    partial void OncRegionChanging(string value);
    partial void OncRegionChanged();
    partial void OnimPhotoChanging(System.Data.Linq.Binary value);
    partial void OnimPhotoChanged();
    partial void OndJoiningDateChanging(System.Nullable<System.DateTime> value);
    partial void OndJoiningDateChanged();
    partial void OndResignationDateChanging(System.Nullable<System.DateTime> value);
    partial void OndResignationDateChanged();
    partial void OncSocialSecurityNoChanging(string value);
    partial void OncSocialSecurityNoChanged();
    partial void OncSupervisorCodeChanging(string value);
    partial void OncSupervisorCodeChanged();
    #endregion
		
		public Employee1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cEmployeeCode", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cEmployeeCode
		{
			get
			{
				return this._cEmployeeCode;
			}
			set
			{
				if ((this._cEmployeeCode != value))
				{
					this.OncEmployeeCodeChanging(value);
					this.SendPropertyChanging();
					this._cEmployeeCode = value;
					this.SendPropertyChanged("cEmployeeCode");
					this.OncEmployeeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vFirstName", DbType="VarChar(20)")]
		public string vFirstName
		{
			get
			{
				return this._vFirstName;
			}
			set
			{
				if ((this._vFirstName != value))
				{
					this.OnvFirstNameChanging(value);
					this.SendPropertyChanging();
					this._vFirstName = value;
					this.SendPropertyChanged("vFirstName");
					this.OnvFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vLastName", DbType="VarChar(20)")]
		public string vLastName
		{
			get
			{
				return this._vLastName;
			}
			set
			{
				if ((this._vLastName != value))
				{
					this.OnvLastNameChanging(value);
					this.SendPropertyChanging();
					this._vLastName = value;
					this.SendPropertyChanged("vLastName");
					this.OnvLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCandidateCode", DbType="Char(6)")]
		public string cCandidateCode
		{
			get
			{
				return this._cCandidateCode;
			}
			set
			{
				if ((this._cCandidateCode != value))
				{
					this.OncCandidateCodeChanging(value);
					this.SendPropertyChanging();
					this._cCandidateCode = value;
					this.SendPropertyChanged("cCandidateCode");
					this.OncCandidateCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vAddress", DbType="VarChar(35)")]
		public string vAddress
		{
			get
			{
				return this._vAddress;
			}
			set
			{
				if ((this._vAddress != value))
				{
					this.OnvAddressChanging(value);
					this.SendPropertyChanging();
					this._vAddress = value;
					this.SendPropertyChanged("vAddress");
					this.OnvAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCity", DbType="Char(20)")]
		public string cCity
		{
			get
			{
				return this._cCity;
			}
			set
			{
				if ((this._cCity != value))
				{
					this.OncCityChanging(value);
					this.SendPropertyChanging();
					this._cCity = value;
					this.SendPropertyChanged("cCity");
					this.OncCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cState", DbType="Char(20)")]
		public string cState
		{
			get
			{
				return this._cState;
			}
			set
			{
				if ((this._cState != value))
				{
					this.OncStateChanging(value);
					this.SendPropertyChanging();
					this._cState = value;
					this.SendPropertyChanged("cState");
					this.OncStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cZip", DbType="Char(10)")]
		public string cZip
		{
			get
			{
				return this._cZip;
			}
			set
			{
				if ((this._cZip != value))
				{
					this.OncZipChanging(value);
					this.SendPropertyChanging();
					this._cZip = value;
					this.SendPropertyChanged("cZip");
					this.OncZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCountryCode", DbType="Char(3)")]
		public string cCountryCode
		{
			get
			{
				return this._cCountryCode;
			}
			set
			{
				if ((this._cCountryCode != value))
				{
					this.OncCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._cCountryCode = value;
					this.SendPropertyChanged("cCountryCode");
					this.OncCountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cPhone", DbType="Char(15)")]
		public string cPhone
		{
			get
			{
				return this._cPhone;
			}
			set
			{
				if ((this._cPhone != value))
				{
					this.OncPhoneChanging(value);
					this.SendPropertyChanging();
					this._cPhone = value;
					this.SendPropertyChanged("cPhone");
					this.OncPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vQualification", DbType="VarChar(20)")]
		public string vQualification
		{
			get
			{
				return this._vQualification;
			}
			set
			{
				if ((this._vQualification != value))
				{
					this.OnvQualificationChanging(value);
					this.SendPropertyChanging();
					this._vQualification = value;
					this.SendPropertyChanged("vQualification");
					this.OnvQualificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dBirthDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dBirthDate
		{
			get
			{
				return this._dBirthDate;
			}
			set
			{
				if ((this._dBirthDate != value))
				{
					this.OndBirthDateChanging(value);
					this.SendPropertyChanging();
					this._dBirthDate = value;
					this.SendPropertyChanged("dBirthDate");
					this.OndBirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cSex", DbType="Char(1)")]
		public System.Nullable<char> cSex
		{
			get
			{
				return this._cSex;
			}
			set
			{
				if ((this._cSex != value))
				{
					this.OncSexChanging(value);
					this.SendPropertyChanging();
					this._cSex = value;
					this.SendPropertyChanged("cSex");
					this.OncSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCurrentPosition", DbType="Char(20)")]
		public string cCurrentPosition
		{
			get
			{
				return this._cCurrentPosition;
			}
			set
			{
				if ((this._cCurrentPosition != value))
				{
					this.OncCurrentPositionChanging(value);
					this.SendPropertyChanging();
					this._cCurrentPosition = value;
					this.SendPropertyChanged("cCurrentPosition");
					this.OncCurrentPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDesignation", DbType="Char(20)")]
		public string cDesignation
		{
			get
			{
				return this._cDesignation;
			}
			set
			{
				if ((this._cDesignation != value))
				{
					this.OncDesignationChanging(value);
					this.SendPropertyChanging();
					this._cDesignation = value;
					this.SendPropertyChanged("cDesignation");
					this.OncDesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cEmailId", DbType="Char(20)")]
		public string cEmailId
		{
			get
			{
				return this._cEmailId;
			}
			set
			{
				if ((this._cEmailId != value))
				{
					this.OncEmailIdChanging(value);
					this.SendPropertyChanging();
					this._cEmailId = value;
					this.SendPropertyChanged("cEmailId");
					this.OncEmailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDepartmentCode", DbType="Char(4)")]
		public string cDepartmentCode
		{
			get
			{
				return this._cDepartmentCode;
			}
			set
			{
				if ((this._cDepartmentCode != value))
				{
					this.OncDepartmentCodeChanging(value);
					this.SendPropertyChanging();
					this._cDepartmentCode = value;
					this.SendPropertyChanged("cDepartmentCode");
					this.OncDepartmentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cRegion", DbType="Char(20)")]
		public string cRegion
		{
			get
			{
				return this._cRegion;
			}
			set
			{
				if ((this._cRegion != value))
				{
					this.OncRegionChanging(value);
					this.SendPropertyChanging();
					this._cRegion = value;
					this.SendPropertyChanged("cRegion");
					this.OncRegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imPhoto", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary imPhoto
		{
			get
			{
				return this._imPhoto;
			}
			set
			{
				if ((this._imPhoto != value))
				{
					this.OnimPhotoChanging(value);
					this.SendPropertyChanging();
					this._imPhoto = value;
					this.SendPropertyChanged("imPhoto");
					this.OnimPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dJoiningDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dJoiningDate
		{
			get
			{
				return this._dJoiningDate;
			}
			set
			{
				if ((this._dJoiningDate != value))
				{
					this.OndJoiningDateChanging(value);
					this.SendPropertyChanging();
					this._dJoiningDate = value;
					this.SendPropertyChanged("dJoiningDate");
					this.OndJoiningDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dResignationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dResignationDate
		{
			get
			{
				return this._dResignationDate;
			}
			set
			{
				if ((this._dResignationDate != value))
				{
					this.OndResignationDateChanging(value);
					this.SendPropertyChanging();
					this._dResignationDate = value;
					this.SendPropertyChanged("dResignationDate");
					this.OndResignationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cSocialSecurityNo", DbType="Char(15)")]
		public string cSocialSecurityNo
		{
			get
			{
				return this._cSocialSecurityNo;
			}
			set
			{
				if ((this._cSocialSecurityNo != value))
				{
					this.OncSocialSecurityNoChanging(value);
					this.SendPropertyChanging();
					this._cSocialSecurityNo = value;
					this.SendPropertyChanged("cSocialSecurityNo");
					this.OncSocialSecurityNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cSupervisorCode", DbType="Char(6)")]
		public string cSupervisorCode
		{
			get
			{
				return this._cSupervisorCode;
			}
			set
			{
				if ((this._cSupervisorCode != value))
				{
					this.OncSupervisorCodeChanging(value);
					this.SendPropertyChanging();
					this._cSupervisorCode = value;
					this.SendPropertyChanged("cSupervisorCode");
					this.OncSupervisorCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Position")]
	public partial class Position : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cPositionCode;
		
		private string _vDescription;
		
		private System.Nullable<int> _iBudgetedStrength;
		
		private System.Nullable<short> _siYear;
		
		private System.Nullable<int> _iCurrentStrength;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncPositionCodeChanging(string value);
    partial void OncPositionCodeChanged();
    partial void OnvDescriptionChanging(string value);
    partial void OnvDescriptionChanged();
    partial void OniBudgetedStrengthChanging(System.Nullable<int> value);
    partial void OniBudgetedStrengthChanged();
    partial void OnsiYearChanging(System.Nullable<short> value);
    partial void OnsiYearChanged();
    partial void OniCurrentStrengthChanging(System.Nullable<int> value);
    partial void OniCurrentStrengthChanged();
    #endregion
		
		public Position()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cPositionCode", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cPositionCode
		{
			get
			{
				return this._cPositionCode;
			}
			set
			{
				if ((this._cPositionCode != value))
				{
					this.OncPositionCodeChanging(value);
					this.SendPropertyChanging();
					this._cPositionCode = value;
					this.SendPropertyChanged("cPositionCode");
					this.OncPositionCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vDescription", DbType="VarChar(35)")]
		public string vDescription
		{
			get
			{
				return this._vDescription;
			}
			set
			{
				if ((this._vDescription != value))
				{
					this.OnvDescriptionChanging(value);
					this.SendPropertyChanging();
					this._vDescription = value;
					this.SendPropertyChanged("vDescription");
					this.OnvDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iBudgetedStrength", DbType="Int")]
		public System.Nullable<int> iBudgetedStrength
		{
			get
			{
				return this._iBudgetedStrength;
			}
			set
			{
				if ((this._iBudgetedStrength != value))
				{
					this.OniBudgetedStrengthChanging(value);
					this.SendPropertyChanging();
					this._iBudgetedStrength = value;
					this.SendPropertyChanged("iBudgetedStrength");
					this.OniBudgetedStrengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siYear", DbType="SmallInt")]
		public System.Nullable<short> siYear
		{
			get
			{
				return this._siYear;
			}
			set
			{
				if ((this._siYear != value))
				{
					this.OnsiYearChanging(value);
					this.SendPropertyChanging();
					this._siYear = value;
					this.SendPropertyChanged("siYear");
					this.OnsiYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iCurrentStrength", DbType="Int")]
		public System.Nullable<int> iCurrentStrength
		{
			get
			{
				return this._iCurrentStrength;
			}
			set
			{
				if ((this._iCurrentStrength != value))
				{
					this.OniCurrentStrengthChanging(value);
					this.SendPropertyChanging();
					this._iCurrentStrength = value;
					this.SendPropertyChanged("iCurrentStrength");
					this.OniCurrentStrengthChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
